# -*- coding: utf-8 -*-
"""Titanic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wz_QSQybiXK4HVhspzguCwWddKRi6tKD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = sns.load_dataset('titanic')

df.head()

df.shape

df.columns

#df.loc[:, ['survived', 'pclass', 'sibsp', 'parch']]
df =df.iloc[:, [0,1, 4, 5,]]

df.head()

df.isnull().sum()

X = df.iloc[:, 1:]
y = df.iloc[:, 0]

X.head()

y.head()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train

y_train

from sklearn.linear_model import LogisticRegression

clf=LogisticRegression()
clf.fit(X_train, y_train)

pred=clf.predict(X_test)

pred

y_test

from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)